parserOptions:
  ecmaVersion: 6
  sourceType: 'module'
  ecmaFeatures:
    impliedStrict: true
    jsx: true

plugins:
  - 'react'

settings:
  react:
    pragma: 'createElement'

env:
  browser: true

rules:
  no-unused-vars: 'error'
  react/jsx-uses-react: 'error'
  react/jsx-uses-vars: 'error'

  no-undef: 'error'
  react/react-in-jsx-scope: 'error'
  react/jsx-no-undef: 'error'

  indent: ['error', 4, {
    SwitchCase: 1
  }]
  semi: 'error'
  no-extra-semi: 'error'
  no-unreachable: 'error'
  eqeqeq: 'error'
  no-var: 'error'
  prefer-const: 'error'
  object-shorthand: 'error'
  constructor-super: 'error'
  no-this-before-super: 'error'
